In [18]:
import cv2
%load_ext autoreload
%autoreload 2
import numpy as np
import torch
from torch_model import Network, Network_org, densenet, Network_1024, Network_1024_without_bev

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
model = Network_org()

In [22]:
x = torch.rand((3, 1, 16, 1024))
y = model(x)
y.shape

torch.Size([3, 1024, 4, 16]) torch.Size([3, 1024, 4, 16])
torch.Size([3, 256, 16, 128]) torch.Size([3, 256, 16, 128])


torch.Size([3, 1, 64, 1024])

In [2]:
locations = []

for i in range(28, 224, 28):
    for j in range(28, 224, 28):
        locations.append([i,j])
len(locations)

49

In [3]:
image = np.load("/home/akshay/bag/bev_64_np/2362.041642299.npy")
#image *= 100.
cv2.imshow("k",image)
cv2.waitKey(0)

FileNotFoundError: [Errno 2] No such file or directory: '/home/akshay/bag/bev_64_np/2362.041642299.npy'

In [ ]:
x = np.load("/home/akshay/bag/range_16/1000.041622004.npy")
print(np.sum(x != 0))
x = np.uint8(x*255)
y = np.load("/home/akshay/bag/range_64_/1000.041622004.npy")
print(np.sum(y != 0))
y = np.uint8(y*255)

cv2.imshow("hi", x)
cv2.imshow("k", y)
cv2.waitKey(0)

In [ ]:
checkpoint = torch.load("/home/akshay/python_carla/weights/checkpoint_dec_4.pth")

In [ ]:
model_main = Network_1024()
model_main.eval()
model_main.load_state_dict(checkpoint['state_dict'])
bev_model = densenet()
bev_model.eval()
x = np.load("/home/akshay/bag/range_16_1024/1000.041622004.npy")
y = np.load("/home/akshay/bag/bev_16_np/1000.041622004.npy")
org = np.load("/home/akshay/bag/range_64_1024/1000.041622004.npy")
org = np.expand_dims(org, axis=0)
bev = np.tile(y, (3,1,1))
print(np.sum(bev != 0))
bev = torch.from_numpy(bev)

range_image_16 = np.expand_dims(x, axis=0)
print(np.sum(range_image_16 != 0))
range_image_16 = torch.from_numpy(range_image_16)
range_image_16 = torch.unsqueeze(range_image_16, axis=0)
bev = torch.unsqueeze(bev, axis=0)

feature = bev_model(bev)
print(torch.sum(feature != 0).item())
out = model_main(range_image_16, feature)
out = out.detach().numpy()
print(np.max(out))

out = np.concatenate([out[0],org], axis=0)
print(out.shape, np.max(org))
np.save("/home/akshay/python_carla/please.npy",out )

In [ ]:
checkpoint = torch.load("/home/akshay/python_carla/weights/checkpoint_dec_3.pth")

In [ ]:
model_main = Network_1024_without_bev()
model_main.eval()
model_main.load_state_dict(checkpoint['state_dict'])

x = np.load("/home/akshay/bag/range_16_1024/1000.041622004.npy")
org = np.load("/home/akshay/bag/range_64_1024/1000.041622004.npy")
org = np.expand_dims(org, axis=0)

range_image_16 = np.expand_dims(x, axis=0)
print(np.sum(range_image_16 != 0))
range_image_16 = torch.from_numpy(range_image_16)
range_image_16 = torch.unsqueeze(range_image_16, axis=0)

print(torch.sum(feature != 0).item())
out = model_main(range_image_16)
out = out.detach().numpy()
print(np.max(out))

out = np.concatenate([out[0],org], axis=0)
print(out.shape, np.max(org))
np.save("/home/akshay/python_carla/please.npy",out )

In [ ]:
please = np.load("/home/akshay/python_carla/please.npy")
please.shape

In [ ]:
data = np.load("/home/akshay/Downloads/carla_ouster_range_image.npy")

In [ ]:
data.shape

In [ ]:
for i in range(data.shape[0]):
    im = data[i]
    im = np.uint8(im)
    cv2.imshow("f",im)
    cv2.waitKey(5)

In [4]:
x = np.load("/home/akshay/bag/range_16/1000.041622004.npy")
x *= 100
x = np.uint8(x)
cv2.imshow("j", x)
y = np.load("/home/akshay/bag/bev_16_np/1000.041622004.npy")
org = np.load("/home/akshay/bag/range_64/1000.041622004.npy")
org *= 100
org = n.uint8(org)
cv2.imshow("a", org)
cv2.waitKey(0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to target thread (0x5556e1f09ec0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to target thread (0x5556e1f09ec0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to target thread (0x5556e1f09ec0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to target thread (0x5556e1f09ec0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to target thread (0x5556e1f09ec0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to target thread (0x5556e1f09ec0)

QObject::moveToThread: Current thread (0x5556e1f09ec0) is not the object's thread (0x5556e1fa69d0).
Cannot move to tar

NameError: name 'n' is not defined

In [1]:
import torch
from chamferdist import ChamferDistance

In [ ]:
cd = ChamferDistance()
x = torch.randn((1, 3, 100)).cuda()
y = torch.randn((1, 3, 109)).cuda()
dist = cd(x, y)
print(dist)

In [17]:
from pytorch3d.loss import chamfer_distance
import torch
x = torch.randn((8, 128000, 3), requires_grad=True).cuda()
y = torch.randn((8, 120000, 3), requires_grad=True).cuda()

In [18]:
loss = chamfer_distance(x, y)[0]

In [19]:
loss

tensor(0.0083, device='cuda:0', grad_fn=<AddBackward0>)

In [11]:
loss.backward()

In [21]:
if isinstance(x, Tensor):
    print("hi")

NameError: name 'Tensor' is not defined

In [26]:
x = torch.arange(0, 10).reshape(-1, 1)
x[x >5] = -133
x

tensor([[   0],
        [   1],
        [   2],
        [   3],
        [   4],
        [   5],
        [-133],
        [-133],
        [-133],
        [-133]])

In [27]:
x = x[torch.where(x != -133)]
x

tensor([0, 1, 2, 3, 4, 5])

In [32]:
x = torch.randint(0, 5, size=(2, 5))
y = torch.randint(0, 5, size=(5,))
x, y, x*y

(tensor([[3, 0, 4, 0, 2],
         [2, 0, 1, 0, 1]]),
 tensor([1, 1, 3, 4, 4]),
 tensor([[ 3,  0, 12,  0,  8],
         [ 2,  0,  3,  0,  4]]))

In [1]:
from MyDataLoader import MyDatasetChamferDistance

In [ ]:
dataset = MyDatasetChamferDistance()